# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestActualTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_actualTest(self):
    self.driver.get("http://127.0.0.1:5500/lms/KiTaab/index.html")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.ID, "searchInput").send_keys("horro")
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(5) .image-container > .image-icon1:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Account").click()
    self.driver.find_element(By.ID, "oname").click()
    self.driver.find_element(By.ID, "oname").send_keys("Raghav")
    self.driver.find_element(By.ID, "oid").click()
    self.driver.find_element(By.ID, "oid").send_keys("fasd")
    self.driver.find_element(By.ID, "s1").click()
    self.driver.find_element(By.ID, "s1").send_keys("adf")
    self.driver.find_element(By.ID, "s2").click()
    self.driver.find_element(By.ID, "s2").send_keys("1")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Subscriptions").click()
  
